version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  service:
    image: {{ cookiecutter.gitlab_registry }}/{{ cookiecutter.gitlab_repository_path }}:dev
    command: echo "ok"
    build:
      context: '.'
      dockerfile: 'Dockerfile'